Entity/BaseEntity.php
<?php

namespace AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Base entity
 *
 * @ORM\MappedSuperclass
 */
abstract class BaseEntity implements BaseEntityInterface
{
    abstract public function __toString();

    public static function __getName()
    {
        $array = explode('\\', static::class);
        return end($array);
    }

    public static function __getNameUnderscore()
    {
        return strtolower(preg_replace('/([^A-Z])([A-Z])/', '$1_$2', static::__getName()));
    }

    public static function getShowColumns()
    {
        return static::getIndexColumns();
    }

    public function getHasTranslatableToString()
    {
        return false;
    }
}

Resources/views/_partial/edit.html.twig
{% extends 'AdminBundle::default.html.twig' %}

{% block breadcrumbsList %}
<a class="breadcrumb-item" href="{{ path('admin_entity_index', { 'className': className }) }}">{{ config.entities[className].title is defined ? config.entities[className].title|transchoice(2) : className|split('\\')|last|humanize|transchoice(2) }}</a>
{% endblock %}

{% block title %}
{{ app.request.get('_route') == 'admin_entity_new' ? 'New record'|trans : entity|transEntity }}
{% endblock %}

{% block content %}
{{ form_start(form) }}
{{ form_widget(form) }}
<div class="form-group row">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
        <button type="submit" name="save" class="btn-success btn mr-3">{{ 'Save'|trans }}</button>
        <a href="{{ app.request.get('_route') == 'admin_entity_new' ? path('admin_entity_index', { 'className': className }) : path('admin_entity_show', { 'className': className, 'id': entity.id }) }}" name="cancel" class="btn-danger btn">
            {{ 'Cancel'|trans }}
        </a>
    </div>
</div>
{{ form_end(form) }}
{% endblock %}

{% block javascripts %}
{{ parent() }}
<script>
    window.CKEDITOR_BASEPATH = '{{ asset('bundles/admin/ckeditor/') }}';
</script>
<script src="{{ asset('bundles/admin/ckeditor/ckeditor.js') }}"></script>
<script>
    CKEDITOR.config.language = '{{ app.request.get('_locale') }}';
    [].forEach.call(document.getElementsByClassName('wysiwyg'), function (wysiwyg) {
        CKEDITOR.replace(wysiwyg);
    });
</script>
{% endblock %}

Resources/views/_partial/entity_link.html.twig
<a href="{{ path('admin_entity_show', { 'className': className, 'id': entity.id }) }}">{{ entity|transEntity }}</a>

Resources/views/_partial/index.html.twig
{% extends 'AdminBundle::default.html.twig' %}

{% block title %}{{ routes[className].title is defined ? routes[className].title|transchoice(2) : className|split('\\')|last|humanize|transchoice(2) }}{% endblock %}

{% block content %}
{% embed 'AdminBundle::_partial/list.html.twig' %}{% endembed %}
{% endblock %}

Resources/views/_partial/list.html.twig
{% if not list is defined %}
{% set placeholder = true %}
{% set list = [] %}
{% else %}
{% set placeholder = false %}
{% endif %}
<table
    class="table table-hover"
    data-dynamic-content="{{ path('admin_entity_list', { 'className': className }) }}"
    data-dynamic-content-placeholder="{% filter escape %}{% include 'AdminBundle::_partial/list_content.html.twig' with { 'className': className, 'placeholder': true, 'columns': columns } %}{% endfilter %}"
    >
    <thead class="thead-sticky">
        <tr>
            <th colspan="{{ columns|length + 1 }}">{% include 'AdminBundle::_partial/list_header.html.twig' with { 'className': className, 'page': page } %}</th>
        </tr>
        {% if placeholder or list|length > 0 %}
        <tr>
            {% include 'AdminBundle::_partial/table_header.html.twig' with { 'columns': columns } %}
        </tr>
        {% endif %}
    </thead>
    {% if not placeholder %}
    {% include 'AdminBundle::_partial/list_content.html.twig' with { 'className': className, 'placeholder': placeholder, 'list': list, 'columns': columns, 'page': page, 'pageCount': pageCount }%}
    {% endif %}
</table>

Resources/views/_partial/list_content.html.twig
{% if not placeholder is defined %}
{% set placeholder = false %}
{% endif %}
<tbody>
{% if placeholder or list|length > 0 %}
    {% if placeholder %}
        <tr>
            <td colspan="{{ columns|length + 1 }}">
                <div class="d-flex justify-content-center">
                    <div class="loader"></div>
                </div>
            </td>
        </tr>
    {% else %}
        {% for entity in list %}
        <tr data-href="{{ path('admin_entity_show', { 'className': className, 'id': entity.id }) }}">
            {% for column in columns %}
            <td>
                {% include 'AdminBundle::_partial/property_value.html.twig' with { entity: entity, column: column } %}
            </td>
            {% endfor %}
            <td class="text-right">
                <a href="{{ path('admin_entity_edit', { 'className': className, 'id': entity.id }) }}" class="btn btn-sm btn-primary">{{ 'Edit'|trans }}</a>
            </td>
        </tr>
        {% endfor %}
    {% endif %}
{% else %}
    <tr>
        <td colspan="{{ columns|length + 1 }}">{{ 'No records found.'|trans}}</td>
    </tr>
{% endif %}
</tbody>
{% if not placeholder and pageCount > 1 %}
{% set lowRange = page %}
{% set hiRange = page %}
{% for i in range(1, 2) %}
    {% if lowRange > 1 %}
        {% set lowRange = lowRange - 1 %}
    {% elseif hiRange < pageCount %}
        {% set hiRange = hiRange + 1 %}
    {% endif %}
    {% if hiRange < pageCount %}
        {% set hiRange = hiRange + 1 %}
    {% elseif lowRange > 1 %}
        {% set lowRange = lowRange - 1 %}
    {% endif %}
{% endfor %}
<tfoot class="tfoot-sticky">
    <tr>
        <td colspan="{{ columns|length + 1 }}">
            <nav aria-label="{{ 'Page navigation'|trans }}">
                <ul class="pagination justify-content-center">
                    <li class="page-item{{ page == 1 ? ' disabled' }}">
                        <a class="page-link" href="{{ path('admin_entity_index', { 'className': className, 'page': (page - 1 > 0 ? page - 1 : 1) }) }}" aria-label="{{ 'Previous'|trans }}" data-page="{{ page - 1 > 0 ? page - 1 : 1 }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% for i in range(lowRange, hiRange) %}
                    <li class="page-item{{ page == i ? ' active'}}"><a class="page-link" href="{{ path('admin_entity_index', { 'className': className, 'page': i }) }}" data-page="{{ i }}">{{ i }}</a></li>
                    {% endfor %}
                    <li class="page-item{{ page == pageCount ? ' disabled' }}">
                        <a class="page-link" href="{{ path('admin_entity_index', { 'className': className, 'page': (page + 1 < pageCount ? page + 1 : pageCount) }) }}" aria-label="{{ 'Next'|trans }}" data-page="{{ page + 1 < pageCount ? page + 1 : pageCount }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </td>
    </tr>
</tfoot>
{% endif %}

Resources/views/_partial/list_filter.html.twig
<form data-dynamic-content-filter>
    <div class="row">
        <div class="col-lg-6">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary" type="button">Hledat</button>
                </span>
            </div>
        </div>
        <div class="col-lg-6 d-flex justify-content-end">
            <a href="{{ path('admin_entity_new', { 'className': className }) }}" class="btn btn-success">Nový záznam</a>
        </div>
    </div>
    <input type="hidden" name="page" value="{{ page }}" />
</form>

Resources/views/_partial/list_header.html.twig
<form data-dynamic-content-filter>
    <div class="row">
        <div class="col-lg-6">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary" type="button">{{ 'Search'|trans }}</button>
                </span>
            </div>
        </div>
        <div class="col-lg-6 d-flex justify-content-end">
            <a href="{{ path('admin_entity_new', { 'className': className }) }}" class="btn btn-success">{{ 'New record'|trans }}</a>
        </div>
    </div>
    <input type="hidden" name="page" value="{{ page }}" />
</form>

Resources/views/_partial/property_value.html.twig
{% set obj = entity %}
{% set property = column.property is defined ? column.property : column %}
{% for key in property|split('.') %}
{% set obj = attribute(obj, key) %}
{% endfor %}
{{ obj|propertyValue(column) }}

Resources/views/_partial/show.html.twig
{% extends 'AdminBundle::default.html.twig' %}

{% block breadcrumbsList %}
<a class="breadcrumb-item" href="{{ path('admin_entity_index', { 'className': className }) }}">{{ config.entities[className].title is defined ? config.entities[className].title|transchoice(2) : className|split('\\')|last|humanize|transchoice(2) }}</a>
{% endblock %}

{% block title %}
{{ entity.hasTranslatableToString ? entity|transEntity : entity }}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6">
        <table class="table">
            <tbody>
                {% for column in columns %}
                    <tr>
                        {% include 'AdminBundle::_partial/table_row.html.twig' with { 'entity': entity, 'column': column, 'header': true } %}
                    </tr>
                {% endfor %}
                <tr><td colspan="2"></td></tr>
                {% set extraColumns = ['createdAt', 'createdBy', 'updatedAt', 'updatedBy'] %}
                {% for extraColumn in extraColumns %}
                {% if attribute(entity, extraColumn) is defined %}
                    <tr>
                        {% include 'AdminBundle::_partial/table_row.html.twig' with { 'entity': entity, 'column': { 'property': extraColumn }, 'header': true } %}
                    </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="form-inline">
    <div class="form-group mr-3">
        <a href="{{ path('admin_entity_edit', { 'className': className, 'id': entity.id }) }}" class="btn btn-primary form-control">{{ 'Edit'|trans }}</a>
    </div>
    <div class="form-group">
        <a href="{{ path('admin_entity_index', { 'className': className }) }}" class="btn btn-danger form-control">{{ 'Back'|trans }}</a>
    </div>
</div>

{% if entity.documents is defined %}
{% include 'AdminBundle::_partial/documents.html.twig' with { 'entity': entity } %}
{% endif %}

{% if entity.comments is defined %}
{% include 'AdminBundle::_partial/comments.html.twig' with { 'entity': entity } %}
{% endif %}
{% endblock %}

Resources/views/_partial/table_header.html.twig
{% for column in columns %}
    <th{{ column.attr is defined ? column.attr|htmlAttributes }}>{{ column.property is defined ? column.property|humanize|trans : column|humanize|trans }}</th>
{% endfor %}
<th></th>

Resources/views/_partial/table_row.html.twig
{% if header is defined and header %}
<th>{{ column.name is defined ? column.name : (column.property is defined ? column.property|split('.')|last|humanize|transchoice(1) : column|split('.')|last|humanize|transchoice(1)) }}</th>
{% endif %}
<td>{% include 'AdminBundle::_partial/property_value.html.twig' with { 'entity': entity, 'column': column } %}</td>